name: routes
version: 0.0.1
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: simple server routing
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_migration
dependencies:
  params: '>=0.0.2 <0.1.0'
  route: '>=0.4.6 <0.5.0'
environment: 
  sdk: ">=0.8.10+6 <2.0.0" 