name: routes
version: 0.1.4
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: simple server routing
homepage: https://github.com/HannesRammer/routes/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  params: "^0.0.3"
    #path: "c:/Projects/Dart/Params"
  route: "^0.4.6"
  route_hierarchical: '>=0.4.22 <1.0.0'
